version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dr_api
    ports:
      - "8000:8000"
    networks:
      - dr_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: dr_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - dr_network

networks:
  dr_network:
    driver: bridge
