services:
  backend:
    build: ./backend
    container_name: retino-backend
    ports:
      - "8000:8000"
    networks:
      - retino-net

  frontend:
    build: ./app
    container_name: retino-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - retino-net

networks:
  retino-net:
    driver: bridge
